# Generated by Django 4.2 on 2025-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1. Sınıf"),
                    (2, "2. Sınıf"),
                    (3, "3. Sınıf"),
                    (4, "4. Sınıf"),
                    (5, "5. Sınıf"),
                    (6, "6. Sınıf"),
                    (7, "7. Sınıf"),
                    (8, "8. Sınıf"),
                    (9, "9. Sınıf"),
                    (10, "10. Sınıf"),
                    (11, "11. Sınıf"),
                    (12, "12. Sınıf"),
                ],
                help_text="Student's current grade (1-12)",
                null=True,
                verbose_name="Grade",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has completed their profile information",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="track",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lgs", "LGS (8. sınıf ve altı)"),
                    ("sayisal", "Sayısal"),
                    ("sozel", "Sözel"),
                ],
                help_text="Academic track (LGS, Sayısal, Sözel)",
                max_length=10,
                null=True,
                verbose_name="Track",
            ),
        ),
    ]
